engines:
  eslint:
    enabled: true

ratings: #Specifies which files/paths will be graded.
  paths:
    - "src/**/*.jsx?"
    - "src/*.jsx?"

exclude_paths: #Paths that you want excluded from our analysis.
  - "src/**/*.test.js"
  - "src/tests.bundle.js"
