language: node_js
node_js:
- 0.12
sudo: false
notifications:
  email: false
cache:
  directories:
  - node_modules
  - bower_components
before_install:
- npm config set spin false
install:
- npm install
script:
- npm test
after_script:
- npm install codeclimate-test-reporter codecov.io
- ./node_modules/.bin/codeclimate < coverage/lcov.info
- ./node_modules/.bin/codecov < coverage/lcov.info
addons:
  sauce_connect: true
  code_climate: true
env:
  global:
  - secure: MhnrJxNUW7pxzzBlWaneF79bNX1JIAkb/5CBk/6etKIjNrhhRc5LCbJalb5kYxBfXzb1ky3L35+/GewaT6P6kHnAvaP6UrIm4VEyL3vPkwaQ7FNaQnKd/JbksBXVxKfnMYBVBiF7MVuCGSDD4ZIzkHl04Ah/lzv6caM+zkbrG1QxKBV7LTlQ6V4KCuFYzXyKUGBE2nV7YanNInQd3f8EOUepMfflsoPOosl+QWHcElv2vjj9pHiQe+t7++DtwOveV937rQ0z9BX4whoNRTpuaMANb2siMp/M9mdYShCElp1MCzi9eTP1fdUS8tsqrHwpXG0NO8SbkFpPBok8O5zogqcOn6gC3xnN5eNHuC5rmaENHVprRvxWoLXfNMvvDsmCZ4QKGFLj245N8cPvVGLrZHla+wvV2iELdbPN8crDgzBvx7KluNYDmC9VhUGTdgqKyPK0GU75NkTlLYoJB+nvlW1xpT2jMjNNsrs+b6eKFwRL+Z80GbfKzMefEU12jRIV2l/gN4Hy4OJw9OGRrXhZ4QprExsl0WLcs+EmqopdWRnE+00l2tTUhvRxIWwFPBs2vWdaXZ7eLuiap3ZSaltTBbjXPkJOUvAGGYDNj7B7PWulUsB50R6LNqLyxUVobqIe10RHoDoO4YdaJV4F9WDdrndeHC4eTZ0FMnkJv0j9v7k=
  - secure: LcuKylJC7Q7bV/XElSVbkmlRN7lY4roJhQOYT418yL8T2TALZEQmz8fRcZIFqbqGXne04B2G8/VI7WWtcN2OP2wcr/N7MQvU0AJBKigCtyvH4qboBdfDipM8ANg6Azste7S6vYqM1Ui7dxwnQQi8vt5zl2p5yJYyokvFaLWT0xF8/Zf307ijqtDw634WNY2PfOopP4WAEqNtfVRwMwlDEwN6N110I2C2Hrlt+RuVi+3oZez94opYL6tpR1ZykIJCWQ5WEQiJoksFG2/yZFSu1S10d3J1NSTpSsVweHzJUk5ExXw6MYVgrhG1Ksr8o519s3L7Xyny8787nzH5N8S8C3O2s7zBm7EAHOWjvdA16clNBm/VTpo6OfEkv2mz80Wyx6sa4YFe0OM9UtlLhFcQZfaxd8aEIjpMGNS16r5GWQexgE9628SJxzDqhr9PvKJO5j09kLAvc/opkdFxOQZMuyVIgZHOoSpQ3HATjOp5aGWJsRXJclP3qvZtCsP5V521yFDDfYOQac0+gg4bnsa1YZVdF1A7ssdR5aYeQssS0rwTFgd8/aYXhqHOiUayIaxHUZ3fmugjrpOkBP6oKL+SXH4+wfb+EE+NXfpXEEMkfiRdACbeH++tpQtPkKWguWT2YeHQ9RIxUg6E5V4VdhdSuGledlUlnrNqBm/Vkt/hx9Y=
  - secure: WHU7xCmp0wW869nrSxRaRnClLrbGy0jKXjOEwDJAPVR7v7dCqjJN47m+HBNAV4jY43bSbMqUNP+jbuFSlT0So59hPTokD2F7TM2n+hr17z94QStUPaUNVZfmH82hChfGLjUzFZWeqanDSxg8InfyuhXmHyLNXhBEhT9A3jV3ChfPk4FFalAeqGK5liZwwp3DuEEFthvooz4wCmfNSE4v+G52dCoF8XYiZ2m8knKHToVfpJQKkRKhyp3wuMTef5jv7x/QXB/q5Fy5RqOqekuOfNWs6/TeQcVHBoTYKlLWZe3aFh1EQmm6TJvirnM29F75qUPhbJG9AI9cd51dzSZrbtLk8t81/4mBw5ulOqPB4n8K0LOeV8mVTA9j+fQYvzLuA/2hNt4yvcFwZ823MhmRiuozp42VYrycGvq8IcTW6Y00VV0ceODyGL6UkDQWTkQ+m4W/u8WL8scO6Q6kCqUwPOYUfID7croirBGcEeNLNKczPDU+JR8pxM2gS5Nh5uedOrYMcy6moZoGYaUYIZau5ytNdOeY0fy8OHxkJUMZIAraiiRfggUMl1DyV/EpLhVwNxO+3RLTjmsUQFrjI/uwifXTzugEGjmOBjE5EgAmHhg7OXa2RkW8EYTAdgHGaAmgxZof1uxncVtLKWUBlUAH+T4qeHlbP4WTC/CXTGNvHDg=
